### PR TITLE
Updated readme.md with deprecation notice

### PR DESCRIPTION
**Pull request by brankopajic**
@rayalex Please add [deprecated] tag in the repo name.

### CODE REVIEW

**Comment by rayalex** [comment]
@brankopajic Is there a replacement library which supersedes this one?

**Comment by brankopajic** [comment]
@rayalex Well, there is [arduino-sdk](https://github.com/allthingstalk/arduino-sdk) which replaces old arduino-client library, but I don't know if it covers everything from arduino-gateway-client library.

**Comment by rayalex** [comment]
@esthoril Can you chime in with your thoughts on this?

**Comment by brankopajic** [comment]
@rayalex My mistake, I misread repo name while answering. There is a replacement library, it's [arduino-lorawan-sdk](https://github.com/allthingstalk/arduino-lorawan-sdk). I'll add it in the deprecation notice paragraph.

cc @esthoril

**Pull request merged**
